require("asteroid_definitions.mercury")
require("asteroid_definitions.venus")
require("asteroid_definitions.earth")
require("asteroid_definitions.luna")
require("asteroid_definitions.mars")
require("asteroid_definitions.asteroid-belt-inner")
require("asteroid_definitions.jupiter")
require("asteroid_definitions.saturn")
require("asteroid_definitions.uranus")
require("asteroid_definitions.neptune")
require("asteroid_definitions.pluto")
-- Place holder for code which returns all asteroid definitions for the solar system.
